- autoload/pum.vim
> Set pos of pum in Vim

- autoload/pum.vim
`:redraw` clears highlight of `'incsearch'`.
This is inconvenient when using ddc.vim in search command line.
The fix is from wilder.nvim.
https://github.com/gelguy/wilder.nvim/blob/f50d79a3f9ef07be3c0c8a0f49faaeea803a8c0c/autoload/wilder/renderer.vim#L10-L15
> Redraw without breaking 'incsearch' in search command line

- autoload/pum.vim
According to Neovim help, `nvim_open_win()` accepts an array specifing border characters, so it should be also supported in pum.vim. Currently some part of code causes type error, so this PR fixes that.
Also, this PR tries to measure precise border size (now border can be non-uniform, you can disable one side of border with empty string as border character). But it's too complecated and fI'm not sure the logic is correct. If you think it should be kept simple, please ignore second commit (7fc575b).
> Add array of border characters support

- autoload/pum.vim
First of all, thank you for quick response!
With padding = true, the right side is trimed for 1 chars. Also, position of highlighting for matching word is wrong.
This PR fixes it.
> Fix pum width and matching highlights

- autoload/pum/map.vim
Unlike built-in popup menu, `pum#map#confirm()` does not close the popup or call autocmd `PumCompleteDone` if the input exactly matches with the `word` of the selected item.
This sometimes make snippet items to not expand correctly.
This PR changes `pum#map#confirm()` to close the popup and call `PumCompleteDone` even if the input exactly matches with the `word` of the selected item.
Use [Shougo/ddc.vim](https://github.com/Shougo/ddc.vim) and [hrsh7th/vim-vsnip](https://github.com/hrsh7th/vim-vsnip).
```vim
let s:dein_dir = expand('<sfile>:h') .. '/dein'
let &runtimepath .= ',' .. s:dein_dir .. '/repos/github.com/Shougo/dein.vim'
call dein#begin(s:dein_dir)
call dein#add('vim-denops/denops.vim')
call dein#add('Shougo/ddc.vim')
call dein#add('Shougo/pum.vim')
call …
```
> Change to complete even if input exactly matches

- autoload/pum.vim
- autoload/pum/popup.vim
Fix for https://github.com/matsui54/denops-popup-preview.vim/issues/16 .
> Include border size for pum#get_pos()

- autoload/pum.vim
- doc/pum.txt
This autocmd is for [denops-popup-preview.vim](https://github.com/matsui54/denops-popup-preview.vim).
I need this autocmd to properly close the preivew window.
> Add PumClose autocmd

- autoload/pum.vim
In [documentation](https://github.com/Shougo/pum.vim/blob/00ce3ea23701cfd8fa3a21d8ee04c4791adc6678/doc/pum.txt#L262-L265), `pum#visible()` will return `v:true` .
But `pum#visible()` returns `1` when pum is displayed.
This behavior cause some problems when called the function from Neovim-lua.
```lua
vim.keymap.set('i', '<CR>', function()
if not vim.fn['pum#visible']() then -- This condition does not work.
return vim.fn['lexima#expand']('<lt>CR>', 'i')
end
return '<Cmd>call pum#map#confirm()<CR>'
end, { expr = true })
```
> Fix `pum#visible()` and `pum#entered()` doesn't return `v:true`

- autoload/pum/util.vim
Return value pattern of `pcall()` is `false, errormsg` or `true, value` and some modules are not compatible to vim value.
For example, `noice.nvim` integration is not work because this problem.
Therefore this PR change to use `select()` and compare type within lua.
> Fix luacheck was always fail

- autoload/pum/map.vim
- doc/pum.txt
After sourcing this script, the content of `g:lines` is expected `['foo']` but `['']`.
This means `CmdlineChanged` autocmd isn't invoked when `pum#map#confirm()` is called.
https://gist.github.com/fa875de95d7e59180c16575e99c21205
- Make not to use `noautocmd` in `s:setcmdline()`.
- Set `skip_count` to notify to completion engine.
> fix: Invoke CmdlineChanged on confirm

- autoload/pum/popup.vim
Both of these bugs occur when pum#_options().padding is true and the start of the completion is in the first column.
> Fix two bugs in command line completion.

- autoload/pum/popup.vim
The byte length of multibyte characters may be larger than max_column calculated by `strdisplaywidth()`.
> Fix calc highlight position

- autoload/pum/popup.vim
SSIA.
Fix #45
The +1 for padding is now explicitly indicated by 'space' and included in max_column.
> Fix to calc highlight position

- autoload/pum/map.vim
- autoload/pum/popup.vim
SSIA
In Neovim if `'laststatus'` is 3, status line of current window (floatwin) will be redrew while `win_execute()`.
> fix: Execute redraw outside of win_execute()

- autoload/pum/popup.vim
Fixed a bug where scrollbars were misaligned when using the border setting.
- pum.vim version(SHA1):d1b9579b4614f65c78c18dd9ac875afd397be867
- OS:Ubuntu 22.04.2 LTS on Windows 10 x86_64
- neovim/Vim `:version` output:NVIM v0.10.0-dev-836+g6d93bdd45-Homebrew
```vim
set rtp+=/path/to/pum.vim
function! g:Create_dummy_items(qty) abort
let items = []
for i in range(1, a:qty)
call add(items, #{ word: 'test' .. i, kind: 'Test', menu: '[test]' })
endfor
return items
endfunction
call pum#set_option(#{
\   max_height: 20,
\   border: 'single',
\ })
inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-Space> <Cmd>call pum#open(col('.'), g:Create_dummy_items(40))<CR>
```
1. Press `<C-Space>` in insert mode
- before  
- after
> Fix scrollbar position when using border. (neovim only)

- autoload/pum.vim
- autoload/pum/map.vim
- autoload/pum/popup.vim
Highlights of `'hlsearch'` overrides `highlight_selected`.
Adjusting priority option of `matchaddpos()` does not resolve the issue because matches always override highlights of items, which uses textprop or extmark.
Replace `matchaddpos()` with other methods such as textprop or extmark.
> fix: Improve highlight_selected

- autoload/pum/popup.vim
Follow up #52
- Use lowest priority for `highlight_selected` like CurosorLine does.
- Replace `strwidth()` with `strlen()` to calculate byte length.
> fix: Follow up #52

- autoload/pum/popup.vim
Thank you for creating so many useful plugins.
I like that your plugins are highly adjustable.
I have fixed what seems to be a bug in this plugin, so could you please check it?
Fixed the part where the highlight_scrollbar setting was overridden to NONE and disabled.
- pum.vim version(SHA1):8d3fd2b5de9166dea16a7cc1a0c1e23e40f63ae1
- OS:Ubuntu 22.04.2 LTS on Windows 10 x86_64
- neovim/Vim `:version` output:NVIM v0.10.0-dev-836+g6d93bdd45-Homebrew
```vim
set rtp+=/path/to/pum.vim
function! g:Create_dummy_items(qty) abort
let items = []
for i in range(1, a:qty)
call add(items, #{ word: 'test' .. i, kind: 'Test', menu: '[test]' })
endfor
return items
endfunction
highlight PmenuCustomSbar ctermfg=11
call pum#set_option(#{
\   max_height: 20,
\   highlight_scrollbar: 'PmenuCustomSbar',
\ …
```
> Fix highlight_scrollbar option handling. (neovim only)

- autoload/pum/map.vim
Unneeded `ModeChanged` fire at `complete()` call in `s:insert_line_complete()`
It breaks ddc.vim since https://github.com/Shougo/ddc.vim/commit/b6e598e63c47f9172ec4f64a21f9d81a32a186a8
Suppress `ModeChanged`
- pum.vim version(SHA1): 19988d249e618808404c8d3fe70e7dcc9b51b784
- OS: Arch Linux
- neovim/Vim `:version` output: NVIM v0.10.0-dev-1301+g30d311ebc-dirty
```vim
" Your minimal .vimrc
set runtimepath^=~/path/to/pum.vim/
function s:enter()
call pum#open(1, [#{word: 'foo'}])
endfunction
autocmd ModeChanged *:i call s:enter()
autocmd ModeChanged * echom expand('<amatch>')
inoremap <C-n> <Cmd>call pum#map#insert_relative(1)<CR>
startinsert!
```
1. Press `<C-n>`
2. insert `foo` but pum re-opened
`autocmd ModeChanged * echom expand('<amatch>')` result at while press `<C-n>`
```
i:ic
ic:i …
```
> fix: prevent unneeded ModeChanged fire at insert_line_complete

- autoload/pum/popup.vim
Since `s:pum_selected_id` was a constant value, it could not be reassigned in the process within `pum#popup#_redraw_selected()`, causing an error.
It was changed to const in commit 71ed0cb, so this PR changes it back to let.
> fix: error of locked `s:pum_selected_id`

- autoload/pum/popup.vim
Currently, the height of the preview window can be too short if text wraps occur.
To solve the problem, I borrowed a piece of code from `matsui54/denops-popup-preview.vim`.
https://github.com/matsui54/denops-popup-preview.vim/blob/5a62ac76478791a86f17ac79f064ab302c41f5eb/autoload/vital/_popup_preview/VS/Vim/Window/FloatingWindow.vim?plain=1#L120-L123
> feat: adjust preview height based on text wrapping

- autoload/pum/popup.vim
- doc/pum.txt
Currently, of the `border` options supported in Vim, only `double` works correctly.
The other options have the following problems:
- If `single` is set, a double line (Vim defaults) is displayed
- If array is set, no border is displayed
Both are caused by incorrect properties of the `popup_create` function.
The `border` property only recognizes 0 or non-zero values, so `borderchars` must be set to specify the border type.  Also, even if `borderchars` is set, if `border` is not set to a non-zero value, the border will not be displayed.
This pull request fixes the above problem.
However, if `&ambiwidth` is not `single` or `&encoding` is not `utf-8`, it will not render correctly, so Vim's default border display of ASCII characters will be used.
Please let me know if there is a problem with …
> Some 'border' options not working in Vim
